version: '3.3'
services:

  db:
    container_name: postgres
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
#    command:
#      - python manage.py migrate
    restart: always
    volumes:
      - ./backend/:/usr/src/app/backend/
      - static_value:/app/static/
      - media_value:/app/media/
    expose:
      - 8000
    depends_on:
    - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/etc/nginx/html/static/
      - media_value:/etc/nginx/html/media/
    depends_on:
      - backend
volumes:
  postgres_data:
  static_value:
  media_value:
